name: Like pizza

on:
  issue_comment:
    types: [created]

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'I like pizza'}}
    steps:
      - name: Like pizza
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: return "I will be string (not JSON) encoded!"