name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust_test
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Check sources & dependencies for errors
        run: cargo check 
      - name: Check correctness of the crate manifest
        run: cargo verify-project
      - name: Check sources for formating errors
        run: cargo fmt --check
        
  build:
    name: Build project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust_test
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update Toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose

  unittests:
    name: Build and Run unittests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust_test
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Run Unit Tests
        run: cargo test --verbose
